#!/usr/bin/env python3
# -*- coding: utf-8 -*-

import rospy
from std_msgs.msg import String

def main():
    rospy.init_node('noeud_controlleur', anonymous=True)
    rospy.loginfo("Demarrage du noeud controleur...")

    command_pub = rospy.Publisher('/command', String, queue_size=10)

    rate = rospy.Rate(1)  # 1 Hz
    while not rospy.is_shutdown():
        command_pub.publish("MOVE_FORWARD")
        rospy.loginfo("Commande envoyee : MOVE_FORWARD")
        rate.sleep()

if __name__ == '__main__':
    try:
        main()
    except rospy.ROSInterruptException:
        pass

